export const API_PATH = {
	MERCHANT: 'merchant',
	AUTH: 'auth',
	IMAGE: 'image',
	PROD_CATEGORIES: 'product-categories',
	PROD_TAGS: 'product-tags',
	PROD: 'products',
	PROD_OPTIONS: 'product-options',
	PROD_VARIANTS: 'product-variants',
	PROD_TYPES: 'product-types',
	CURRENCIES: 'currencies',
	COUNTRIES: 'countries',
	SETTINGS: 'settings',
	CRM_USERS: 'crm-users',
	ORDERS: 'orders',
	SALES: 'sales',
	SUMM_ORDERS: 'summ-orders',
	SUMM_SALES: 'summ-sales',
};
